name: Run Rest Assured Test Cases

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'  # Use a stable version like 17
          distribution: 'temurin'
          cache: maven

      - name: Install Maven
        run: |
          curl -sL https://www.apache.org/dyn/closer.cgi?action=download&filename=maven/maven-3/3.8.8/binaries/apache-maven-3.8.8-bin.zip -o maven.zip
          Expand-Archive -Path maven.zip -DestinationPath $env:RUNNER_TEMP
          echo "MAVEN_HOME=$env:RUNNER_TEMP\apache-maven-3.8.8" >> $env:GITHUB_ENV
          echo "$env:RUNNER_TEMP\apache-maven-3.8.8\bin" >> $env:GITHUB_PATH

      - name: Run tests
        run: mvn clean test